#!bin/bash/

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
    printf "\npre-commit: About to create the first commit...\n"
else
    against=$(git hash-object -t tree /dev/null)
    printf "\npre-commit: About to create a new commit...\n"
fi

printf  "pre-commit: Testing for whitespace errors 😨\n"

if git diff-index --check --cached $against --
then
	printf "pre-commit: No whitespace errors 😀\n"
	exit 0
else
	printf "pre-commit: Aborting commit due to whitespace errors ☹️\n"
	exit 1
fi
